name: Release hive-2.3

on:
  push:
    tags:
      - '2.3.*-onehouse-*'

env:
  AWS: "aws"

permissions:
  id-token: write
  contents: read

jobs:
  generate-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Set TAG_PRESENT_IN_COMMIT
        run: echo "TAG_PRESENT_IN_COMMIT=$(git tag --contains $COMMIT_HASH | head -1)" >> $GITHUB_ENV
      - name: Set VERSION
        run: echo "VERSION=$TAG_PRESENT_IN_COMMIT" >> $GITHUB_ENV
      - name: Print Version
        run: echo "$VERSION"
      - name: Fail if version not set
        if: env.VERSION == ''
        run: exit 1
      - id: version
        run: echo "version=$VERSION" >> $GITHUB_OUTPUT
  publish-jar:
    needs: generate-version
    uses: ./.github/workflows/publish-jar.yaml
    secrets: inherit
    with:
      version: ${{needs.generate-version.outputs.version}}
